spring.application.name=comments

# Database configuration
spring.datasource.url=jdbc:h2:file:./data/comments
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true